---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: 1-demo
  namespace: flux-system
spec:
  interval: 20s
  ref:
    branch: 1-demo
  url: https://github.com/ayyan2009/bb-app-source
